# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# Default values for hybrid-cluster-manager-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imageOverrides:
    mcm_compliance: ""
    grc_ui: ""
    grc_ui_api: ""
  pullPolicy: Always
  

arch:
  - amd64
  - ppc64le
  - s390x
replicas: 1
pullSecret: null
nodeSelector:
  enabled: false
  os: ""
  customLabelSelector: ""
  customLabelValue: ""

compliance:
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
grcui:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
grcuiapi:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
