# Copyright (c) 2020 Red Hat, Inc.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    kubernetes.io/ingress.class: ingress-open-cluster-management
  name: {{ .Release.Name }}-grcui
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-grcui
            port:
              number: 3000
        path: /multicloud/policies
        pathType: ImplementationSpecific
